name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  http: ^1.5.0
  video_player: ^2.9.5
  file_picker: ^10.3.3
  path_provider: ^2.1.2
  share_plus: ^7.2.1

  # Le package SDK Natif officiel
  tiktok_sdk_v2: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
